- name: Mask passwords and change destination folder
  hosts: all
  tasks:
    - name: Create destination folder if it does not exist
      file:
        path: "{{ NEW_DEST_DIR }}"
        state: directory

    - name: Read and mask passwords in message broker property files
      command: cat "{{ HOME_DIR }}/FenergoMessageBroker/config/{{ item }}"
      register: file_contents
      with_items:
        - message-broker-avox-properties.xml
        - message-broker-bpsi-properties.xml
        - message-broker-canonical-properties.xml
        - message-broker-core-properties.xml
        - message-broker-cra-properties.xml
        - message-broker-filenet-properties.xml
        - message-broker-icdms-properties.xml
        - message-broker-inflight-properties.xml
        - message-broker-nack-properties.xml
        - message-broker-scheduler-properties.xml
        - message-broker-scistamping-properties.xml
        - message-broker-sqltasks-properties.xml
      changed_when: false
      delegate_to: localhost

    - name: Mask passwords and write to new destination folder
      copy:
        content: "{{ item.stdout | regex_replace('password=.*', 'password=****') }}"
        dest: "{{ NEW_DEST_DIR }}/{{ item.item }}"
      with_items: "{{ file_contents.results }}"
      tags: mask_passwords