- name: Separate and process XML files
  hosts: fbservers
  tags: masking
  vars:
    source_dir_pre: "/colt/devops/config/pre-deployment"
    source_dir_post: "/colt/devops/config/post-deployment"
    destination_dir_pre: "/colt/devops/config/masked_pre-deployment"
    destination_dir_post: "/colt/devops/config/masked_post-deployment"

  tasks:
    - name: Create base destination directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ destination_dir_pre }}"
        - "{{ destination_dir_post }}"

    - name: Find -properties.xml files in pre-deployment
      find:
        paths: "{{ source_dir_pre }}"
        patterns: "*-properties.xml"
      register: properties_files_pre

    - name: Find camel.xml files in pre-deployment
      find:
        paths: "{{ source_dir_pre }}"
        patterns: "*camel*.xml"
      register: camel_files_pre

    - name: Find -properties.xml files in post-deployment
      find:
        paths: "{{ source_dir_post }}"
        patterns: "*-properties.xml"
      register: properties_files_post

    - name: Find camel.xml files in post-deployment
      find:
        paths: "{{ source_dir_post }}"
        patterns: "*camel*.xml"
      register: camel_files_post

    - name: Gather file statistics for pre-deployment -properties.xml files
      stat:
        path: "{{ item.path }}"
      with_items: "{{ properties_files_pre.files }}"
      register: stat_properties_files_pre

    - name: Gather file statistics for pre-deployment camel.xml files
      stat:
        path: "{{ item.path }}"
      with_items: "{{ camel_files_pre.files }}"
      register: stat_camel_files_pre

    - name: Gather file statistics for post-deployment -properties.xml files
      stat:
        path: "{{ item.path }}"
      with_items: "{{ properties_files_post.files }}"
      register: stat_properties_files_post

    - name: Gather file statistics for post-deployment camel.xml files
      stat:
        path: "{{ item.path