- name: Separate and process XML files
  hosts: fbservers
  tags: masking_date
  vars:
    source_dir_pre: "/colt/devops/config/pre-deployment"
    source_dir_post: "/colt/devops/config/post-deployment"
    destination_dir_pre: "/colt/devops/config/masked_pre-deployment"
    destination_dir_post: "/colt/devops/config/masked_post-deployment"

  tasks:
    - name: Create base destination directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ destination_dir_pre }}"
        - "{{ destination_dir_post }}"

    - name: Find -properties.xml files in pre-deployment
      find:
        paths: "{{ source_dir_pre }}"
        patterns: "*-properties.xml"
      register: properties_files_pre

    - name: Find camel.xml files in pre-deployment
      find:
        paths: "{{ source_dir_pre }}"
        patterns: "*camel*.xml"
      register: camel_files_pre

    - name: Find -properties.xml files in post-deployment
      find:
        paths: "{{ source_dir_post }}"
        patterns: "*-properties.xml"
      register: properties_files_post

    - name: Find camel.xml files in post-deployment
      find:
        paths: "{{ source_dir_post }}"
        patterns: "*camel*.xml"
      register: camel_files_post

    - name: Gather file statistics for pre-deployment -properties.xml files
      stat:
        path: "{{ item.path }}"
      with_items: "{{ properties_files_pre.files }}"
      register: stat_properties_files_pre

    - name: Gather file statistics for pre-deployment camel.xml files
      stat:
        path: "{{ item.path }}"
      with_items: "{{ camel_files_pre.files }}"
      register: stat_camel_files_pre

    - name: Gather file statistics for post-deployment -properties.xml files
      stat:
        path: "{{ item.path }}"
      with_items: "{{ properties_files_post.files }}"
      register: stat_properties_files_post

    - name: Gather file statistics for post-deployment camel.xml files
      stat:
        path: "{{ item.path }}"
      with_items: "{{ camel_files_post.files }}"
      register: stat_camel_files_post

    - name: Convert mtime to formatted date
      set_fact:
        mtime_date_pre: "{{ item.stat.mtime | int | strftime('%d-%m-%y') }}"
      with_items: "{{ stat_properties_files_pre.results }}"
      register: date_conversion_pre

    - name: Convert mtime to formatted date for camel files
      set_fact:
        mtime_date_camel_pre: "{{ item.stat.mtime | int | strftime('%d-%m-%y') }}"
      with_items: "{{ stat_camel_files_pre.results }}"
      register: date_conversion_camel_pre

    - name: Create date-based directories for pre-deployment -properties.xml files
      file:
        path: "{{ destination_dir_pre }}/config_{{ item.mtime_date_pre }}"
        state: directory
        mode: '0755'
      with_items: "{{ date_conversion_pre.results }}"

    - name: Create date-based directories for pre-deployment camel.xml files
      file:
        path: "{{ destination_dir_pre }}/config_{{ item.mtime_date_camel_pre }}"
        state: directory
        mode: '0755'
      with_items: "{{ date_conversion_camel_pre.results }}"

    - name: Copy pre-deployment -properties.xml files to date-based directories
      shell: cp -p "{{ item.item.path }}" "{{ destination_dir_pre }}/config_{{ item.mtime_date_pre }}/{{ item.item.path | basename }}"
      with_items: "{{ date_conversion_pre.results }}"
      ignore_errors: yes

    - name: Copy pre-deployment camel.xml files to date-based directories
      shell: cp -p "{{ item.item.path }}" "{{ destination_dir_pre }}/config_{{ item.mtime_date_camel_pre }}/{{ item.item.path | basename }}"
      with_items: "{{ date_conversion_camel_pre.results }}"
      ignore_errors: yes

    - name: Mask passwords in pre-deployment -properties.xml files
      shell: |
        find {{ destination_dir_pre }}/config_* -type f -name "*-properties.xml" -exec sed -i 's/\s\s*/ /g' -e 's/(<entry[^>]* name="[^"]*assword"[^>]* value=")[^"]*("[^>]*>)/\1*********\2/g' -e 's/(<[^>]* password="|password=&quot;)[^"]*("[^>]*>)/\1******\2/g' -e 's/&quot;/"/g' {} +
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Convert mtime to formatted date for post-deployment -properties.xml files
      set_fact:
        mtime_date_post: "{{ item.stat.mtime | int | strftime('%d-%m-%y') }}"
      with_items: "{{ stat_properties_files_post.results }}"
      register: date_conversion_post

    - name: Convert mtime to formatted date for post-deployment camel files
      set_fact:
        mtime_date_camel_post: "{{ item.stat.mtime | int | strftime('%d-%m-%y') }}"
      with_items: "{{ stat_camel_files_post.results }}"
      register: date_conversion_camel_post

    - name: Create date-based directories for post-deployment -properties.xml files
      file:
        path: "{{ destination_dir_post }}/config_{{ item.mtime_date_post }}"
        state: directory
        mode: '0755'
      with_items: "{{ date_conversion_post.results }}"

    - name: Create date-based directories for post-deployment camel.xml files
      file:
        path: "{{ destination_dir_post }}/config_{{ item.mtime_date_camel_post }}"
        state: directory
        mode: '0755'
      with_items: "{{ date_conversion_camel_post.results }}"

    - name: Copy post-deployment -properties.xml files to date-based directories
      shell: cp -p "{{ item.item.path }}" "{{ destination_dir_post }}/config_{{ item.mtime_date_post }}/{{ item.item.path | basename }}"
      with_items: "{{ date_conversion_post.results }}"
      ignore_errors: yes

    - name: Copy post-deployment camel.xml files to date-based directories
      shell: cp -p "{{ item.item.path }}" "{{ destination_dir_post }}/config_{{ item.mtime_date_camel_post }}/{{ item.item.path | basename }}"
      with_items: "{{ date_conversion_camel_post.results }}"
      ignore_errors: yes

    - name: Mask passwords in post-deployment -properties.xml files
      shell: |
        find {{ destination_dir_post }}/config_* -type f -name "*-properties.xml" -exec sed -i 's/\s\s*/ /g' -e 's/(<entry[^>]* name="[^"]*assword"[^>]* value=")[^"]*("[^>]*>)/\1*********\2/g' -e 's/(<[^>]* password="|password=&quot;)[^"]*("[^>]*>)/\1******\2/g' -e 's/&quot;/"/g' {} +
      args:
        executable: /bin/bash
      ignore_errors: yes
