---
- name: Install and configure Nginx
  hosts: fbservers
  gather_facts: false

  vars:
    nginx_dir: "/colt/devops-nginx-server"
    nginx_download_dir: "{{ nginx_dir }}/goldenversions"
    nginx_install_dir: "{{ nginx_download_dir }}/nginx-1.20.1"
    export_command: "export GV_INSTALL_DIR={{ nginx_dir }}"

  tasks:
    - name: Create directories and set environment variable
      shell: |
        mkdir -p {{ nginx_dir }}
        {{ export_command }}
      args:
        executable: /bin/bash
      tags: install-nginx

    - name: Copy nginx.sh script
      copy:
        src: files/nginx.sh
        dest: "{{ nginx_download_dir }}/nginx.sh"
        mode: '0755'
      tags: install-nginx

    - name: Execute nginx.sh script
      shell: "./nginx.sh"
      args:
        chdir: "{{ nginx_download_dir }}"
        executable: /bin/bash
      register: nginx_install
      tags: install-nginx

    - name: Debug Nginx installation
      debug:
        var: nginx_install
      tags: install-nginx

    - name: Copy nginx configuration files recursively
      copy:
        src: files/nginx_config/
        dest: "{{ nginx_install_dir }}/config/"
        recurse: yes
      notify: Restart Nginx
      tags: install-nginx

    - name: Copy web files recursively
      copy:
        src: files/html/
        dest: "{{ nginx_install_dir }}/html/"
        recurse: yes
      notify: Restart Nginx
      tags: install-nginx

    - name: Start Nginx server
      shell: "./nginx -p {{ nginx_install_dir }} -c {{ nginx_install_dir }}/config/nginx.conf"
      args:
        chdir: "{{ nginx_install_dir }}/sbin"
        executable: /bin/bash
      notify: Restart Nginx
      tags: install-nginx

  handlers:
    - name: Restart Nginx
      shell: "./nginx -s reload -p {{ nginx_install_dir }} -c {{ nginx_install_dir }}/config/nginx.conf"
      args:
        chdir: "{{ nginx_install_dir }}/sbin"
        executable: /bin/bash
      tags: install-nginx