- name: Separate and process XML files
  hosts: fbservers
  tags: masking
  vars:
    source_dir: "/colt/devops/config/pre-deployment"
    destination_dir: "/colt/devops/config/masked_pre-deployment"

  tasks:
    - name: Create properties and camel directories in destination
      file:
        path: "{{ destination_dir }}/{{ item }}"
        state: directory
      with_items:
        - properties
        - camel

    - name: Find all -properties.xml files
      find:
        paths: "{{ source_dir }}"
        patterns: "*-properties.xml"
      register: properties_files

    - name: Find all camel.xml files
      find:
        paths: "{{ source_dir }}"
        patterns: "*camel*.xml"
      register: camel_files

    - name: Mask passwords in properties files and copy to destination
      command: "cat {{ item.path }}"
      register: file_content
      delegate_to: localhost
      failed_when: false
      with_items: "{{ properties_files.files }}"
      when: item.stat.exists

    - name: Write masked properties files to destination
      copy:
        content: "{{ file_content.stdout | regex_replace('password=.*', 'password=****') }}"
        dest: "{{ destination_dir }}/properties/{{ item.path | basename }}"
      with_items: "{{ properties_files.files }}"
      delegate_to: localhost
      when: item.stat.exists

    - name: Copy camel files to destination
      copy:
        src: "{{ item.path }}"
        dest: "{{ destination_dir }}/camel/{{ item.path | basename }}"
      with_items: "{{ camel_files.files }}"

    - name: Log missing properties files
      debug:
        msg: "Properties file not found: {{ item }}"
      when: properties_files.matched == 0

    - name: Log missing camel files
      debug:
        msg: "Camel file not found: {{ item }}"
      when: camel_files.matched == 0