- name: Separate and process XML files
  hosts: fbservers
  tags: masking
  vars:
    deployments:
      - src: "/colt/devops/config/pre-deployment"
        dest: "/colt/devops/config/masked_pre-deployment"
      - src: "/colt/devops/config/post-deployment"
        dest: "/colt/devops/config/masked_post-deployment"

  tasks:
    - name: Create directories in destination
      file:
        path: "{{ item.dest }}/{{ sub_dir }}"
        state: directory
        mode: '0755'
      loop: "{{ deployments | map(attribute='dest') | product(['properties', 'camel']) | list }}"
      loop_control:
        label: "{{ item[0] }}/{{ item[1] }}"
      vars:
        sub_dir: "{{ item[1] }}"

    - name: Find -properties.xml files
      find:
        paths: "{{ item.src }}"
        patterns: "*-properties.xml"
      register: properties_files
      loop: "{{ deployments }}"
      loop_control:
        label: "{{ item.src }}"

    - name: Find camel.xml files
      find:
        paths: "{{ item.src }}"
        patterns: "*camel*.xml"
      register: camel_files
      loop: "{{ deployments }}"
      loop_control:
        label: "{{ item.src }}"

    - name: Copy -properties.xml files to properties directory
      copy:
        src: "{{ item.path }}"
        dest: "{{ item.dest }}/properties/{{ item.path | basename }}"
        owner: coltuser
        group: coltuser
        mode: '0755'
      loop: "{{ properties_files.results | map(attribute='files') | flatten }}"
      vars:
        dest: "{{ deployments[loop.index0].dest }}"

    - name: Copy camel.xml files to camel directory
      copy:
        src: "{{ item.path }}"
        dest: "{{ item.dest }}/camel/{{ item.path | basename }}"
        owner: coltuser
        group: coltuser
        mode: '0755'
      loop: "{{ camel_files.results | map(attribute='files') | flatten }}"
      vars:
        dest: "{{ deployments[loop.index0].dest }}"

    - name: Mask passwords in properties files
      shell: |
        cd {{ item }}/properties
        for file in *-properties.xml; do
          cat "$file" | sed 's/\s\s*/ /g' | \
          sed -E 's/(<entry[^>]* name="[^"]*assword"[^>]* value=")[^"]*("[^>]*>)/\1*********\2/g' | \
          sed -E 's/(<[^>]* password="|password=&quot;)[^"]*("[^>]*>)/\1******\2/g' | \
          sed -E 's/&quot;/"/g' > "$file.tmp" && mv "$file.tmp" "$file"
        done
      args:
        executable: /bin/bash
      loop: "{{ deployments | map(attribute='dest') }}"