- name: Separate and process XML files
  hosts: fbservers
  tags: masking
  vars:
    source_dir: "/colt/devops/config/pre-deployment"
    destination_dir: "/colt/devops/config/masked_pre-deployment"

  tasks:
    - name: Create properties and camel directories in destination
      file:
        path: "{{ destination_dir }}/{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - properties
        - camel

    - name: Find -properties.xml files
      find:
        paths: "{{ source_dir }}"
        patterns: "*-properties.xml"
      register: properties_files

    - name: Find camel.xml files
      find:
        paths: "{{ source_dir }}"
        patterns: "*camel*.xml"
      register: camel_files

    - name: Copy -properties.xml files to properties directory
      shell: cp -p "{{ item.path }}" "{{ destination_dir }}/properties/{{ item.path | basename }}"
      with_items: "{{ properties_files.files }}"
      ignore_errors: yes

    - name: Copy camel.xml files to camel directory
      shell: cp -p "{{ item.path }}" "{{ destination_dir }}/camel/{{ item.path | basename }}"
      with_items: "{{ camel_files.files }}"
      ignore_errors: yes

    - name: Mask passwords in properties files
      shell: |
        cd {{ destination_dir }}/properties
        for file in *-properties.xml; do
          cat "$file" | sed 's/\s\s*/ /g' | \
          sed -E 's/(<entry[^>]* name="[^"]*assword"[^>]* value=")[^"]*("[^>]*>)/\1*********\2/g' | \
          sed -E 's/(<[^>]* password="|password=&quot;)[^"]*("[^>]*>)/\1******\2/g' | \
          sed -E 's/&quot;/"/g' > "$file.tmp" && mv "$file.tmp" "$file"
        done
      args:
        executable: /bin/bash
      ignore_errors: yes